### ISSUE TITLE
感觉你以做一个模板了

### ISSUE THREAD

**Issue by HPDell** [CS-Tao/whu-library-seat-mobile#1]
可以把这个项目公共部分抽出来，做一个vue的模板😂然后再开发这类由前端打包的手机APP的话直接套用就好了

**Comment by CS-Tao** [comment]
啊不能用了吗，之后又得折腾一波了...这个模板我倒是找到一个: [https://github.com/vuetifyjs/cordova](https://github.com/vuetifyjs/cordova)，虽然 init 后我一次都没有 yarn 成功😂(不过这个可能是在国内的原因，然后 fork 了一份寻思着以后改一下)

**Comment by HPDell** [comment]
那个模板感觉没有你这个配置的好哈哈

**Comment by CS-Tao** [comment]
还不能正常调试，差了很多配置😂
