### ISSUE TITLE
github点星认证失败

### ISSUE THREAD

**Issue by samar1tan** [CS-Tao/whu-library-seat-mobile#3]
1.6.6版本复制粘贴tokens后报错a.find is not a function

**Comment by CS-Tao** [comment]
@samar1tan 我试了几次没问题，你再试两次看看？

如果还有这个问题，你看看方不方便截图或录屏给我看一下，或者把手机型号和系统版本号给我一下

**Comment by samar1tan** [comment]
@CS-Tao 估计是之前的手机太老了

**Comment by CS-Tao** [comment]
> @CS-Tao 估计是之前的手机太老了

看来这条评论是用新手机发的了🤪

**Comment by CS-Tao** [comment]
此 issue 暂时关闭，有别的同学遇到此类问题麻烦新加 issue
